name: spatial
channels:
  - plotly
  - anaconda
  - apple
  - defaults
  - conda-forge
dependencies:
  - affine=2.3.1
  - aom=3.5.0
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.8
  - attrs=22.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - blosc=1.21.1
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.4.3
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - cartopy=0.21.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charls=2.3.4
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - cryptography=37.0.4
  - curl=7.83.1
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2022.5.0
  - dav1d=1.0.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.10.0
  - expat=2.4.8
  - fiona=1.8.21
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.1
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2022.3.0
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.3
  - imagecodecs=2022.8.8
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - ipykernel=6.15.1
  - ipyleaflet=0.17.2
  - ipympl=0.9.2
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json-c=0.16
  - jsonschema=4.14.0
  - jupyter=1.0.0
  - jupyter_client=7.3.5
  - jupyter_console=6.4.4
  - jupyter_core=4.11.1
  - jupyterlab_pygments=0.2.2
  - jxrlib=1.1
  - kealib=1.4.15
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libcxx=14.0.6
  - libdap4=3.20.6
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.5.1
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.72.1
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libpq=14.5
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.9.2
  - libzlib=1.2.12
  - libzopfli=1.0.3
  - llvm-openmp=14.0.4
  - locket=1.0.0
  - lxml=4.9.1
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - munch=2.5.0
  - munkres=1.1.4
  - nbclient=0.6.7
  - nbconvert=7.0.0
  - nbconvert-core=7.0.0
  - nbconvert-pandoc=7.0.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.8.6
  - notebook=6.4.12
  - nspr=4.32
  - nss=3.78
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - osmnx=1.2.2
  - packaging=21.3
  - pandas=1.4.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - plotly=5.10.0
  - poppler=22.04.0
  - poppler-data=0.4.11
  - postgresql=14.5
  - proj=9.0.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - prompt_toolkit=3.0.30
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.13.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python_abi=3.9
  - pytz=2022.2.1
  - pywavelets=1.3.0
  - pyzmq=23.2.1
  - rasterio=1.3.2
  - readline=8.1.2
  - requests=2.28.1
  - rtree=1.0.0
  - scikit-image=0.19.2
  - send2trash=1.8.0
  - setuptools=65.3.0
  - shapely=1.8.4
  - six=1.16.0
  - snappy=1.1.9
  - snuggs=1.4.7
  - soupsieve=2.3.2.post1
  - sqlite=3.39.2
  - stack_data=0.4.0
  - tenacity=8.0.1
  - terminado=0.15.0
  - threadpoolctl=3.1.0
  - tifffile=2022.10.10
  - tiledb=2.11.1
  - tinycss2=1.1.1
  - tk=8.6.12
  - toolz=0.11.2
  - tornado=6.2
  - traitlets=5.3.0
  - traittypes=0.2.1
  - tzcode=2022c
  - tzdata=2022c
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - xarray=2022.6.0
  - xerces-c=3.2.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.8.1
  - zlib=1.2.12
  - zlib-ng=2.0.6
  - zstd=1.5.2
  - pip:
      - absl-py==1.4.0
      - albumentations==1.3.0
      - awscli==1.25.90
      - blessings==1.7
      - boto3==1.24.89
      - botocore==1.27.89
      - bqplot==0.12.36
      - branca==0.6.0
      - cachetools==5.3.0
      - colorama==0.4.4
      - colour==0.1.5
      - configobj==5.0.8
      - contourpy==1.1.0
      - cython==0.29.32
      - dill==0.3.6
      - docutils==0.16
      - earthengine-api==0.1.348
      - ee==0.2
      - ee-extra==0.0.15
      - eerepr==0.0.4
      - et-xmlfile==1.1.0
      - everett==1.0.3
      - exif==1.6.0
      - ffmpeg-python==0.2.0
      - filelock==3.10.7
      - folium==0.14.0
      - future==0.18.3
      - gdal==3.5.2
      - gdown==4.7.1
      - geeadd==0.5.6
      - geedim==1.7.0
      - geemap==0.22.1
      - geocoder==1.38.1
      - geojson==3.0.1
      - geopandas==0.10.2
      - google-api-core==2.11.0
      - google-api-python-client==2.82.0
      - google-auth==2.16.3
      - google-auth-httplib2==0.1.0
      - google-auth-oauthlib==0.4.6
      - google-cloud-core==2.3.2
      - google-cloud-storage==2.7.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.4.1
      - googleapis-common-protos==1.59.0
      - grpcio==1.56.0
      - httplib2==0.22.0
      - imageio==2.22.1
      - ipyevents==2.0.1
      - ipyfilechooser==0.6.0
      - ipytree==0.2.2
      - ipywidgets==7.7.4
      - jmespath==1.0.1
      - joblib==1.3.1
      - jupyterlab-widgets==1.1.3
      - logzero==1.7.0
      - markdown==3.4.3
      - matplotlib==3.6.1
      - multiprocess==0.70.14
      - numpy==1.23.3
      - oauthlib==3.2.2
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.6.0.66
      - openpyxl==3.1.2
      - pandarallel==1.6.3
      - patsy==0.5.3
      - pillow==9.3.0
      - plum-py==0.8.5
      - protobuf==3.19.6
      - psutil==5.9.3
      - py==1.11.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycocotools==2.0.5
      - pycrs==1.0.2
      - pydantic==1.10.2
      - pygeos==0.13
      - pyperclip==1.8.2
      - pyproj==3.4.0
      - pystac==1.6.1
      - python-box==7.0.1
      - pyyaml==5.4.1
      - qudida==0.0.4
      - ratelim==0.1.6
      - requests-oauthlib==1.3.1
      - retry==0.9.2
      - rsa==4.7.2
      - s3transfer==0.6.0
      - sankee==0.2.3
      - scikit-learn==1.3.0
      - scipy==1.9.2
      - scooby==0.7.1
      - seaborn==0.12.2
      - spatial-kde==0.1.0
      - statsmodels==0.13.5
      - tabulate==0.9.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - torch==1.12.1
      - torchvision==0.13.1
      - tqdm==4.64.1
      - triangle==20200424
      - typer==0.4.2
      - typing-extensions==4.4.0
      - uritemplate==4.1.1
      - werkzeug==2.3.6
      - whitebox==2.2.0
      - whiteboxgui==2.2.0
      - widgetsnbextension==3.6.3
