name: spatial2
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.1
  - alsa-lib=1.2.6.1
  - anyio=3.5.0
  - aom=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.8
  - attr=2.5.1
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - blosc=1.21.1
  - boost-cpp=1.74.0
  - bottleneck=1.3.5
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.4.3
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - cartopy=0.21.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charls=2.3.4
  - charset-normalizer=2.1.1
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.0.0
  - contourpy=1.0.5
  - cryptography=37.0.4
  - curl=7.83.1
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2022.5.0
  - dav1d=1.0.0
  - dbus=1.13.18
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.10.0
  - expat=2.4.8
  - fftw=3.3.9
  - fiona=1.8.21
  - flit-core=3.7.1
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.1
  - freetype=2.12.1
  - freexl=1.0.6
  - fsspec=2022.3.0
  - gdal=3.5.1
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.72.1
  - glib-tools=2.72.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.3
  - imagecodecs=2022.8.8
  - imageio=2.19.3
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - ipykernel=6.15.1
  - ipyleaflet=0.17.2
  - ipympl=0.9.2
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jack=1.9.18
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.6
  - jsonschema=4.14.0
  - jupyter=1.0.0
  - jupyter_client=7.3.5
  - jupyter_console=6.4.4
  - jupyter_core=4.11.1
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.16.5
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.64
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libcurl=7.83.1
  - libcxx=14.0.6
  - libcxxabi=14.0.6
  - libdap4=3.20.6
  - libdb=6.2.32
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.3.4
  - libgcc-ng=13.1.0
  - libgdal=3.5.1
  - libgfortran-ng=11.3.0
  - libgfortran5=11.3.0
  - libglib=2.72.1
  - libgomp=13.1.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.5
  - librttopo=1.1.0
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.9.2
  - libzlib=1.2.12
  - libzopfli=1.0.3
  - llvm-openmp=14.0.4
  - locket=1.0.0
  - lxml=4.9.1
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclassic=0.4.8
  - nbclient=0.6.7
  - nbconvert=7.0.0
  - nbconvert-core=7.0.0
  - nbconvert-pandoc=7.0.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.8.6
  - notebook=6.4.12
  - notebook-shim=0.2.2
  - nspr=4.32
  - nss=3.78
  - numexpr=2.7.3
  - numpy=1.25.1
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - osmnx=1.2.2
  - packaging=21.3
  - pandas=1.4.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - plotly=5.10.0
  - ply=3.11
  - pooch=1.4.0
  - poppler=22.04.0
  - poppler-data=0.4.11
  - portaudio=19.6.0
  - postgresql=14.5
  - proj=9.0.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - prompt_toolkit=3.0.30
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.13.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.9.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python_abi=3.9
  - pytz=2022.2.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - pyzmq=23.2.1
  - qt-main=5.15.4
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - rasterio=1.3.2
  - readline=8.1.2
  - requests=2.28.1
  - rtree=1.0.0
  - scikit-image=0.19.2
  - scipy=1.10.1
  - send2trash=1.8.0
  - setuptools=65.3.0
  - shapely=1.8.4
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - snuggs=1.4.7
  - soupsieve=2.3.2.post1
  - sqlite=3.39.2
  - stack_data=0.4.0
  - tenacity=8.0.1
  - terminado=0.15.0
  - threadpoolctl=3.1.0
  - tifffile=2022.10.10
  - tiledb=2.11.1
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.11.2
  - tornado=6.2
  - traitlets=5.3.0
  - traittypes=0.2.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzcode=2022c
  - tzdata=2022c
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xarray=2022.6.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.8.1
  - zlib=1.2.12
  - zlib-ng=2.0.6
  - zstd=1.5.2
  - pip:
    - blessings==1.7
    - bqplot==0.12.40
    - cachetools==5.3.1
    - colour==0.1.5
    - earthengine-api==0.1.360
    - ee==0.2
    - eerepr==0.0.4
    - et-xmlfile==1.1.0
    - future==0.18.3
    - geemap==0.24.4
    - geocoder==1.38.1
    - google-api-core==2.11.1
    - google-api-python-client==2.95.0
    - google-auth==2.22.0
    - google-auth-httplib2==0.1.0
    - google-cloud-core==2.3.3
    - google-cloud-storage==2.10.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.5.0
    - googleapis-common-protos==1.59.1
    - httplib2==0.22.0
    - ipyevents==2.0.1
    - ipyfilechooser==0.6.0
    - ipytree==0.2.2
    - openpyxl==3.1.2
    - patsy==0.5.3
    - protobuf==4.23.4
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pyperclip==1.8.2
    - python-box==7.0.1
    - ratelim==0.1.6
    - rsa==4.9
    - scikit-learn==1.3.0
    - scooby==0.7.2
    - seaborn==0.12.2
    - statsmodels==0.14.0
    - tabulate==0.9.0
    - uritemplate==4.1.1
